# Generated by Django 4.2.6 on 2023-10-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(blank=True, help_text='actual return date', null=True),
        ),
    ]
