# Generated by Django 4.2.6 on 2023-10-15 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='additonal_info',
            new_name='additional_info',
        ),
    ]
