# Generated by Django 4.2.6 on 2023-10-14 05:02

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
